### PR TITLE
Add setRateTolerance method (#36)

### LINKED ISSUE #36: Add `setRateTolerance` method
There needs to be a method to set the rate tolerance in the contract.

### PR DESCRIPTION
**Pull request by r5n**
adds `setRateTolerance` in `contracts/REXMarket.sol` as with onlyOwner check
closes #36

### CODE REVIEW

**Review by rashtrakoff — CHANGES_REQUESTED** [review]
Are you sure you pushed the right file ? This is `REXTwoWayMarket.sol`. Also the latest contracts are on branch `ida-fees-2` so you might be better of adding/pushing the code to that branch. Please ping me or @mikeghen on our discord server for more details.

**Comment by r5n** [comment]
Ahh alright, I see that you did it already.

**Comment by r5n** [comment]
also yeah, I pushed the wrong file, my bad.

**Comment by mikeghen** [comment]
This PR had nothing so I closed it

**Pull request closed without merging**
