### PR TITLE
Fix for Unspent unspent `underlayingInputToken` after distribution

### PR DESCRIPTION
**Pull request by shreyaspapi**
## Changes Made:
- Renamed the function _swapForGas to _swapRemainingForGas
- Added two new events: REXDistribution and REXSubsideDistribution
- Moved the function _upgradeTokens to its own method

### CODE REVIEW

**Review by mikeghen — CHANGES_REQUESTED** [review]
This is really good, Thanks for cleaning up all that code too. I think the problem has moved from having a surplus `inputToken` to having a surplus of `MATIC`. I don't see anywhere the surplus `MATIC` that isn't transfer. I think you have a leak where MATIC will accumulate and be lost. In the current state, left over `inputToken` is swapped in the next round. Here the left over MATIC seems to remain in the contract. 

Take a look and see if I'm making sense @shreyaspapi

**Comment by mikeghen** [comment]
Another comment from discord:

My thought is rename `gelatoFeeShare` to `gasBudgetShare` and let the surplus MATIC accumulate to make the next round execute sooner? A `gasBugetShare` caps the amount of input spent on gas (currently 1%), so if there's surplus from the last round, can it be used on the next round to execute sooner. Potentially using less that 1% of that rounds input. This method should make the % of input used for gas a little variable and potentially could see a % that's less than gasBudgetShare

**Comment by shreyaspapi** [comment]
As for the suggestion to rename `gelatoFeeShare` to `gasBudgetShare`, I think it's a good idea, and I've already made that change in the code.

Regarding the idea of accumulating surplus matic and using it in the next round to execute sooner, I thought about it, but the way the whole process is working currently, the next distribution will happen even sooner than now, so I'm not sure it's necessary to do this. Plus, we don't have to worry about gas costs getting variable and higher in some days

**Comment by mikeghen** [comment]
@shreyaspapi I think implementing a gelato resolver is probably a better idea to address this issue, the change is left over because right now gelato polls every minute, a resolver should be able to execute it right away.

**Pull request closed without merging**
