### PR TITLE
Subsidy Tokens and output tokens testing

### PR DESCRIPTION
**Pull request by vaibhavgeek**
This is in respect to issue https://github.com/Ricochet-Exchange/ricochet-protocol/issues/45 and makes sure that balance of subsidy tokens increase as well.

### CODE REVIEW

**Comment by vaibhavgeek** [comment]
```
Balance of  Admin
usdcx:  731556634563863859364
outputx:  3980300145579996397420
ric tokens: 3980300145579996397420


Balance of  Admin
usdcx:  730167205547957509308
outputx:  3980535458528846052454
ric tokens: 3980535458528846052454
```

**Review by josealonso — COMMENTED** [review]
I would explain in code that USDC uses six decimals.
```
const USDC_DECIMALS: number = 6;
await tp.submitValue(TELLOR_USDC_REQUEST_ID, 10 ** USDC_DECIMALS);
```
And
```
const SECONDS_IN_ONE_HOUR: number = 60 * 60;
await traveler.advanceTimeAndBlock(SECONDS_IN_ONE_HOUR);
```

These are minor changes, anyway.

I didn't compile it, but you get the idea.

**Comment by vaibhavgeek** [comment]
> I would explain in code that USDC uses six decimals.
> 
> ```
> const USDC_DECIMALS: number = 6;
> await tp.submitValue(TELLOR_USDC_REQUEST_ID, 10 ** USDC_DECIMALS);
> ```
> 
> And
> 
> ```
> const SECONDS_IN_ONE_HOUR: number = 60 * 60;
> await traveler.advanceTimeAndBlock(SECONDS_IN_ONE_HOUR);
> ```
> 
> They are minor changes, anyway.
> 
> I didn't compile it, but you get the idea.

This is for typescript. I feel for v2, let's make sure the tests are properly working for every crucial functionality.

**Comment by josealonso** [comment]
You might want to use the time simulation inside the *helpers* directory instead of the *@openzeppelin/test-helpers* library. Take a look at the file *bank.ts*, that library is used there. @rashtrakoff and I try to use *ethers* instead of *web3js*, but @mikeghen uses *web3js* because he's so used to it. I don't know which one is used by the other developers. 
```
await increaseTime(60 * 60 * 24 * 2 + 10);
```

Also, if you are using *ethers*, you can use *ethers.BigNumber.from()* instead of *BN()*
```
assert((await bankInstance2.getRoleMemberCount(KEEPER_ROLE)).eq(ethers.BigNumber.from(2)));
```

**Comment by josealonso** [comment]
@rashtrakoff, do you know if the remaining developers are using *ethers* for their tests ?

**Comment by rashtrakoff** [comment]
> @rashtrakoff, do you know if the remaining developers are using *ethers* for their tests ? 

Do you mean in Ricochet or in general ? As far as I know in general everyone prefer to use Ethers compared to web3. In Ricochet, I guess you, me, @vaibhavgeek and @mikeghen are the only people who wrote tests so I think Ethers prevails.

**Comment by josealonso** [comment]
> > @rashtrakoff, do you know if the remaining developers are using _ethers_ for their tests ?
> 
> Do you mean in Ricochet or in general ? As far as I know in general everyone prefer to use Ethers compared to web3. In Ricochet, I guess you, me, @vaibhavgeek and @mikeghen are the only people who wrote tests so I think Ethers prevails.

I didn't know the other Ricochet developers didn't write tests. It's important to always use *ethers*, then. Mike has to deal with all the contracts logic, so he's allowed to use either one, hahaha

**Pull request merged**
