### PR TITLE
#108  #115 constants scripts, remove artefacts from git

### LINKED ISSUE #108: Use Constants in Deploy Scripts
This tasks involves replacing all the constants hard coded in the scripts with constants from misc/Constants.ts

### LINKED ISSUE #115: Remove `artifacts` from Git
Somehow the `artifacts` directory has slipped into the git history so PRs keep including a lot of noise from changes to this directory. This issue is to remove the `artifacts` directory from the git history so it no longer gets included in PRs.

### PR DESCRIPTION
**Pull request by gitChimp88**
Now requiring constants from ts file in the correct way.
Updated new script file deploy-launchpad.js

removed artefacts from git - 
git rm -r --cached .
git add .

### CODE REVIEW

**Comment by gitChimp88** [comment]
also includes fix for  #115

**Comment by josealonso** [comment]
@gitChimp88, can you explain briefly how you removed the *artifacts* directory from git. I want to solve it in my local. Thanks.

**Review by josealonso — COMMENTED** [review]
@gitChimp88, the *TELLOR_IDs* have to be replaced by constants too. If the id is not in the **Constants.ts** file, just add it. *Tellor* is the oracle used by Ricochet, similar to *Chainlink*. Each token has a different identifier.

**Comment by gitChimp88** [comment]
@josealonso You're right I just updated the pr with the teller id's, also left a short line in the description for how artifacts were removed.

**Review by josealonso — COMMENTED** [review]
@gitChimp88, sorry to bother you again. But it has to be *TELLOR_WBTC_REQUEST_ID* not *TELLOR_REQUEST_ID*. Otherwise, we can't know  which token is associated to that identifier.

**Comment by gitChimp88** [comment]
@josealonso No problem i've given it the correct name now

**Review by josealonso — APPROVED** [review]
Good work, @gitChimp88 !!

**Pull request merged**
